#define VERSION_YEAR			2025
#define VERSION_MAJOR 			1
#define VERSION_MINOR 			0
#define VERSION_REVISION		0
#define VERSION_BUILD			0

#define _VERSION_TEXT_STR2(x)	#x
#define _VERSION_TEXT_STR(x)	_VERSION_TEXT_STR2(x)
#define VERSION_TEXT			_VERSION_TEXT_STR(VERSION_MAJOR.VERSION_MINOR.VERSION_REVISION.VERSION_BUILD)
